services:
  frontend:
    container_name: react-frontend
    build: .
    ports:
    - "5173:5173"
    volumes:
    - .:/app
    - /app/node_modules
    restart: unless-stopped
  # backend: 
  #     container_name: fastapi-backend
  #     build: ./backend
  #     ports:
  #     - "8000:8000"
  #     volumes:
  #     - ./backend:/app
  #     restart: unless-stopped